### ISSUE TITLE
Radeon more like Skideon

### ISSUE THREAD

**Issue by SoldierMC** [RadeonClientOfficial/Radeon-v1.2-Open-source-edition#4]
Control+C is a common [computer command](https://en.wikipedia.org/wiki/Command_(computing)). It is generated by pressing the C key while holding down the [Ctrl](https://en.wikipedia.org/wiki/Control_key) key on most [computer keyboards](https://en.wikipedia.org/wiki/Computer_keyboards).

**Comment by M3gaPixel** [comment]
In computing, Control-V is a key stroke with a variety of uses including generation of a control character in ASCII code, also known as the synchronous idle character. The key stroke is generated by pressing the V key while holding down the Ctrl key on a computer keyboard
